import 'package:calculator_mvc/model/button_category.dart';
import 'package:calculator_mvc/model/button_config.dart';

class ButtonConfigRepository {
  static List<ButtonConfig> buttons = [
    ButtonConfig("c", ButtonCategory.function,
        (calculatorController) => calculatorController.clear()),
    ButtonConfig("⌫", ButtonCategory.function,
        (calculatorController) => calculatorController.backspace()),
    ButtonConfig("%", ButtonCategory.operation,
        (calculatorController) => calculatorController.percent()),
    ButtonConfig("÷", ButtonCategory.operation,
        (calculatorController) => calculatorController.divide()),
    ButtonConfig("7", ButtonCategory.number,
        (calculatorController) => calculatorController.inputNumber("7")),
    ButtonConfig("8", ButtonCategory.number,
        (calculatorController) => calculatorController.inputNumber("8")),
    ButtonConfig("9", ButtonCategory.number,
        (calculatorController) => calculatorController.inputNumber("9")),
    ButtonConfig("x", ButtonCategory.operation,
        (calculatorController) => calculatorController.multiply()),
    ButtonConfig("7", ButtonCategory.number,
        (calculatorController) => calculatorController.inputNumber("4")),
    ButtonConfig("8", ButtonCategory.number,
        (calculatorController) => calculatorController.inputNumber("5")),
    ButtonConfig("9", ButtonCategory.number,
        (calculatorController) => calculatorController.inputNumber("6")),
    ButtonConfig("-", ButtonCategory.operation,
        (calculatorController) => calculatorController.subtract()),
    ButtonConfig("7", ButtonCategory.number,
        (calculatorController) => calculatorController.inputNumber("1")),
    ButtonConfig("8", ButtonCategory.number,
        (calculatorController) => calculatorController.inputNumber("2")),
    ButtonConfig("9", ButtonCategory.number,
        (calculatorController) => calculatorController.inputNumber("3")),
    ButtonConfig("+", ButtonCategory.operation,
        (calculatorController) => calculatorController.add()),
    ButtonConfig("00", ButtonCategory.number,
        (calculatorController) => calculatorController.inputNumber("00")),
    ButtonConfig("0", ButtonCategory.number,
        (calculatorController) => calculatorController.inputNumber("0")),
    ButtonConfig(",", ButtonCategory.number,
        (calculatorController) => calculatorController.inputDot()),
    ButtonConfig("=", ButtonCategory.result,
        (calculatorController) => calculatorController.calculate()),
  ];
}
