import 'package:calculator_mvc/model/calculator_button_category.dart';
import 'package:calculator_mvc/model/calculator_button_config.dart';

class CalculatorButtonConfigRepository {
  static List<CalculatorButtonConfig> buttons = [
    CalculatorButtonConfig("c", CalculatorButtonCategory.function,
        (calculatorController) => calculatorController.clear()),
    CalculatorButtonConfig("⌫", CalculatorButtonCategory.function,
        (calculatorController) => calculatorController.backspace()),
    CalculatorButtonConfig("%", CalculatorButtonCategory.operation,
        (calculatorController) => calculatorController.percent()),
    CalculatorButtonConfig("÷", CalculatorButtonCategory.operation,
        (calculatorController) => calculatorController.divide()),
    CalculatorButtonConfig("7", CalculatorButtonCategory.number,
        (calculatorController) => calculatorController.inputNumber("7")),
    CalculatorButtonConfig("8", CalculatorButtonCategory.number,
        (calculatorController) => calculatorController.inputNumber("8")),
    CalculatorButtonConfig("9", CalculatorButtonCategory.number,
        (calculatorController) => calculatorController.inputNumber("9")),
    CalculatorButtonConfig("x", CalculatorButtonCategory.operation,
        (calculatorController) => calculatorController.multiply()),
    CalculatorButtonConfig("4", CalculatorButtonCategory.number,
        (calculatorController) => calculatorController.inputNumber("4")),
    CalculatorButtonConfig("5", CalculatorButtonCategory.number,
        (calculatorController) => calculatorController.inputNumber("5")),
    CalculatorButtonConfig("6", CalculatorButtonCategory.number,
        (calculatorController) => calculatorController.inputNumber("6")),
    CalculatorButtonConfig("-", CalculatorButtonCategory.operation,
        (calculatorController) => calculatorController.subtract()),
    CalculatorButtonConfig("1", CalculatorButtonCategory.number,
        (calculatorController) => calculatorController.inputNumber("1")),
    CalculatorButtonConfig("2", CalculatorButtonCategory.number,
        (calculatorController) => calculatorController.inputNumber("2")),
    CalculatorButtonConfig("3", CalculatorButtonCategory.number,
        (calculatorController) => calculatorController.inputNumber("3")),
    CalculatorButtonConfig("+", CalculatorButtonCategory.operation,
        (calculatorController) => calculatorController.add()),
    CalculatorButtonConfig("00", CalculatorButtonCategory.number,
        (calculatorController) => calculatorController.inputNumber("00")),
    CalculatorButtonConfig("0", CalculatorButtonCategory.number,
        (calculatorController) => calculatorController.inputNumber("0")),
    CalculatorButtonConfig(",", CalculatorButtonCategory.number,
        (calculatorController) => calculatorController.dot()),
    CalculatorButtonConfig("=", CalculatorButtonCategory.result,
        (calculatorController) => calculatorController.calculate()),
  ];
}
